### ISSUE TITLE
Learn how to use .gitignore ;-)

### ISSUE THREAD

**Issue by NDevox** [TedJohansson/bbd#1]
There are several files here that shouldn't really be put up on git.

e.g. the python bin directory, your bin folder and the settings.py of the django site.

The last one is because it contains your private key, which should remain private... exposing it causes numerous vulnerabilities to be exposed on your site.

I can make a pull request if you want with this but it is really simple and something you should learn to do.

**Comment by teddelin** [comment]
I learned how to .gitignore I have removed private information
