### ISSUE TITLE
Inherit User from django.contrib.auth.models

### ISSUE THREAD

**Issue by NDevox** [TedJohansson/bbd#2]
Django comes prepacked with a load of useful authentication stuff including a User model.

You can find it here: https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#extending-the-existing-user-model

This is for the `LoginDetails` model in bbd.users.models.py

You can see the definition of a User here:

https://github.com/django/django/blob/master/django/contrib/auth/models.py#L297

L297 = AbstractUser (which User inherits from).

L366 is the actual User definition

In general the recommended best practice is to have two separate models.

One which is the authentication model (User). And one which holds personal data for the person. They can link as a OneToOne field (Foreign Key) but it just provides that little bit more of an abstraction layer.

Obviously you don't have anything other than auth fields right now.

Other thing - You are using plain text passwords in a database (which has an exposed private key on this repo...).

The real way to store a password is to hash it with a hashing algorithm and a salt. Store the hashed password, the salt and the algo used. This way you can't easily find the actual password but can still check if the person knows it (by hashing what they pass to you with the salt and see if it matches the hashed password originally given).

**Comment by teddelin** [comment]
This has now been implemented no way to register yet.
